
services:
  redis:
    image: redis:latest
    container_name: "Submission_Redis"
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight:latest
    container_name: "Redis_GUI"
    ports:
      - "5540:5540"
    depends_on:
      - redis

