services:
  shared-rabbit:
    image: rabbitmq:management-alpine
    container_name: shared-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - "5672:5672"   # <--- MAPPED TO 5673
      - "15672:15672" # Management UI (http://localhost:15672)

volumes:
  formschema_data: