global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'formschema-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['formschema-app:8080']

  # Uncomment when services are ready
  # - job_name: 'submission-service'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: ['submission-app:8080']

  # - job_name: 'lead-service'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: ['lead-app:8080']
